# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='description_html',
        ),
    ]
