# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0002_presentation_unpublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='exclusive',
            field=models.BooleanField(default=False, help_text='Set to true if this is the only event during this timeslot'),
        ),
    ]
