# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0002_presentation_unpublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
