# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0003_slot_exclusive'),
        ('symposion_schedule', '0003_auto_20161113_1530'),
    ]

    operations = [
    ]
