# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0005_auto_20161210_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='track',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Track'),
        ),
    ]
