# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 03:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As you would like it to appear in the conference programme.', max_length=100, verbose_name='Name')),
                ('biography', models.TextField(blank=True, help_text="This will appear on the conference website and in the programme.  Please write in the third person, eg 'Alice is a Moblin hacker...', 150-200 words. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.", verbose_name='Biography')),
                ('biography_html', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True, help_text="Have you had any experience presenting elsewhere? If so, we'd like to know. Anything you put here will only be seen by the organisers and reviewers; use it to convince them why they should accept your proposal. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.", verbose_name='Speaking experience')),
                ('experience_html', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='speaker_photos', verbose_name='Photo')),
                ('telephone', models.CharField(help_text="The conference team will need this to contact you during the conference week. If you don't have one, or do not wish to provide it, then enter NONE in this field.", max_length=15)),
                ('homepage', models.URLField(blank=True, help_text='Your home page, if you have one')),
                ('twitter_username', models.CharField(blank=True, help_text='Your Twitter account', max_length=15)),
                ('accessibility', models.TextField(blank=True, help_text="Please describe any special accessibility requirements that you may have. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.", verbose_name='Accessibility requirements')),
                ('accessibility_html', models.TextField(blank=True)),
                ('travel_assistance', models.BooleanField(default=False, help_text='Check this box if you require assistance to travel to Hobart to present your proposed sessions.', verbose_name='Travel assistance required')),
                ('accommodation_assistance', models.BooleanField(default=False, help_text='Check this box if you require us to provide you with student-style accommodation in order to present your proposed sessions.', verbose_name='Accommodation assistance required')),
                ('agreement', models.BooleanField(default=False, help_text='I agree to the terms and conditions of attendance, and I have read, understood, and agree to act according to the standards set forth in our Code of Conduct ')),
                ('annotation', models.TextField(verbose_name='Annotation')),
                ('invite_email', models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='Invite_email')),
                ('invite_token', models.CharField(db_index=True, max_length=40, verbose_name='Invite token')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Created')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
