# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0004_auto_20170810_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='label',
            field=models.CharField(max_length=256, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
    ]
