# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0005_auto_20171013_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultnotification',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
    ]
