# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0002_proposalsection_anonymous'),
        ('symposion_proposals', '0002_auto_20170811_1903'),
    ]

    operations = [
    ]
